name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-format:
    name: Lint & Format Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier Check
        run: npm run format -- --check

  build:
    name: Build Next.js
    runs-on: ubuntu-latest
    needs: lint-format
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js Project
        run: npm run build
